name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
         sudo apt-get update
         sudo apt-get install libgsl-dev
         mkdir build
         cd build
         cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: |
          cd build
          make -j
    - name: test
      run: build/sot -n 1024 -d 2 -c -o test.dat
